title: "J Gross Portfolio"
description: "Showcasing my projects and skills in computer science"
remote_theme: alshedivat/al-folio@v0.3.1
plugins:
- jekyll-remote-theme 
baseurl: "/Portfolio" 
url: "https://unavrgjoe.github.io" 
author: 
  name: "Joseph Gross"
