title: "J Gross Portfolio"
description: "Showcasing my projects and skills in computer science"
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
baseurl: "/Portfolio" # Replace <repository-name> with your repo name
url: "https://unavrgjoe.github.io" # Replace <your-username> with your GitHub username
author: 
  name: "Joseph Gross"
