title: "J Gross Portfolio"
description: "Showcasing my projects and skills in computer science"
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme 
baseurl: "/Portfolio" 
url: "https://unavrgjoe.github.io" 
author: 
  name: "Joseph Gross"
