title: "Joseph Gross — Portfolio"
description: "Unity/Systems • RN/Expo • Edgegap • Supabase"  #change

remote_theme: daattali/beautiful-jekyll@6.0.1 
plugins:
- jekyll-remote-theme 
baseurl: "/Portfolio" 
url: "https://unavrgjoe.github.io" 
site-css: /assets/styles.css
author: 
  name: "Joseph Gross"


navbar-links:
  # Projects: "/Portfolio/projects/"
  Résumé: "/assets/resume.pdf"